// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.SwerveBaseJ;
    

import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainfrontLeftDirMotor;
    public static SpeedController driveTrainfrontLeftSpeedMotor;
    public static SpeedController driveTrainfrontRightDirMotor;
    public static SpeedController driveTrainfrontRightSpeedMotor;
    public static SpeedController driveTrainrearLeftDirMotor;
    public static SpeedController driveTrainrearLeftSpeedMotor;
    public static SpeedController driveTrainrearRightDirMotor;
    public static SpeedController driveTrainrearRightSpeedMotor;
    public static AnalogPotentiometer encoderSubsystemfrontLeftPot;
    public static AnalogPotentiometer encoderSubsystembackLeftPot;
    public static AnalogPotentiometer encoderSubsystemfrontRightPot;
    public static AnalogPotentiometer encoderSubsystembackRightPot;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainfrontLeftDirMotor = new VictorSP(0);
        LiveWindow.addActuator("DriveTrain", "frontLeftDirMotor", (VictorSP) driveTrainfrontLeftDirMotor);
        
        driveTrainfrontLeftSpeedMotor = new VictorSP(1);
        LiveWindow.addActuator("DriveTrain", "frontLeftSpeedMotor", (VictorSP) driveTrainfrontLeftSpeedMotor);
        
        driveTrainfrontRightDirMotor = new VictorSP(2);
        LiveWindow.addActuator("DriveTrain", "frontRightDirMotor", (VictorSP) driveTrainfrontRightDirMotor);
        
        driveTrainfrontRightSpeedMotor = new VictorSP(3);
        LiveWindow.addActuator("DriveTrain", "frontRightSpeedMotor", (VictorSP) driveTrainfrontRightSpeedMotor);
        
        driveTrainrearLeftDirMotor = new VictorSP(4);
        LiveWindow.addActuator("DriveTrain", "rearLeftDirMotor", (VictorSP) driveTrainrearLeftDirMotor);
        
        driveTrainrearLeftSpeedMotor = new VictorSP(5);
        LiveWindow.addActuator("DriveTrain", "rearLeftSpeedMotor", (VictorSP) driveTrainrearLeftSpeedMotor);
        
        driveTrainrearRightDirMotor = new VictorSP(6);
        LiveWindow.addActuator("DriveTrain", "rearRightDirMotor", (VictorSP) driveTrainrearRightDirMotor);
        
        driveTrainrearRightSpeedMotor = new VictorSP(7);
        LiveWindow.addActuator("DriveTrain", "rearRightSpeedMotor", (VictorSP) driveTrainrearRightSpeedMotor);
        
        encoderSubsystemfrontLeftPot = new AnalogPotentiometer(0, 360.0, 0.0);
        LiveWindow.addSensor("EncoderSubsystem", "frontLeftPot", encoderSubsystemfrontLeftPot);
        
        encoderSubsystembackLeftPot = new AnalogPotentiometer(1, 360.0, 0.0);
        LiveWindow.addSensor("EncoderSubsystem", "backLeftPot", encoderSubsystembackLeftPot);
        
        encoderSubsystemfrontRightPot = new AnalogPotentiometer(2, 360.0, 0.0);
        LiveWindow.addSensor("EncoderSubsystem", "frontRightPot", encoderSubsystemfrontRightPot);
        
        encoderSubsystembackRightPot = new AnalogPotentiometer(3, 360.0, 0.0);
        LiveWindow.addSensor("EncoderSubsystem", "backRightPot", encoderSubsystembackRightPot);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
