// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.SwerveBaseJ;
    

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainfrontLeftDirMotor;
    public static SpeedController driveTrainfrontLeftSpeedMotor;
    public static SpeedController driveTrainfrontRightDirMotor;
    public static SpeedController driveTrainfrontRigthSpeedMotor;
    public static SpeedController driveTrainrearLeftDirMotor;
    public static SpeedController driveTrainrearLeftSpeedMotor;
    public static SpeedController driveTrainrearRightDirMotor;
    public static SpeedController driveTrainrearRightSpeedMotor;
    public static DigitalInput encoderSubsystemfrontLeftDir;
    public static DigitalInput encoderSubsystemfrontRightDir;
    public static DigitalInput encoderSubsystemrearLeftDir;
    public static DigitalInput encoderSubsystemrearRightDir;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainfrontLeftDirMotor = new VictorSP(0);
        LiveWindow.addActuator("DriveTrain", "frontLeftDirMotor", (VictorSP) driveTrainfrontLeftDirMotor);
        
        driveTrainfrontLeftSpeedMotor = new VictorSP(1);
        LiveWindow.addActuator("DriveTrain", "frontLeftSpeedMotor", (VictorSP) driveTrainfrontLeftSpeedMotor);
        
        driveTrainfrontRightDirMotor = new VictorSP(2);
        LiveWindow.addActuator("DriveTrain", "frontRightDirMotor", (VictorSP) driveTrainfrontRightDirMotor);
        
        driveTrainfrontRigthSpeedMotor = new VictorSP(3);
        LiveWindow.addActuator("DriveTrain", "frontRigthSpeedMotor", (VictorSP) driveTrainfrontRigthSpeedMotor);
        
        driveTrainrearLeftDirMotor = new VictorSP(4);
        LiveWindow.addActuator("DriveTrain", "rearLeftDirMotor", (VictorSP) driveTrainrearLeftDirMotor);
        
        driveTrainrearLeftSpeedMotor = new VictorSP(5);
        LiveWindow.addActuator("DriveTrain", "rearLeftSpeedMotor", (VictorSP) driveTrainrearLeftSpeedMotor);
        
        driveTrainrearRightDirMotor = new VictorSP(6);
        LiveWindow.addActuator("DriveTrain", "rearRightDirMotor", (VictorSP) driveTrainrearRightDirMotor);
        
        driveTrainrearRightSpeedMotor = new VictorSP(7);
        LiveWindow.addActuator("DriveTrain", "rearRightSpeedMotor", (VictorSP) driveTrainrearRightSpeedMotor);
        
        encoderSubsystemfrontLeftDir = new DigitalInput(0);
        LiveWindow.addSensor("EncoderSubsystem", "frontLeftDir", encoderSubsystemfrontLeftDir);
        
        encoderSubsystemfrontRightDir = new DigitalInput(2);
        LiveWindow.addSensor("EncoderSubsystem", "frontRightDir", encoderSubsystemfrontRightDir);
        
        encoderSubsystemrearLeftDir = new DigitalInput(4);
        LiveWindow.addSensor("EncoderSubsystem", "rearLeftDir", encoderSubsystemrearLeftDir);
        
        encoderSubsystemrearRightDir = new DigitalInput(6);
        LiveWindow.addSensor("EncoderSubsystem", "rearRightDir", encoderSubsystemrearRightDir);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
