// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.SwerveBaseJ.subsystems;

import org.usfirst.frc1073.SwerveBaseJ.RobotMap;
import org.usfirst.frc1073.SwerveBaseJ.commands.*;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem implements PIDSubsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController frontLeftDirMotor = RobotMap.driveTrainfrontLeftDirMotor;
    SpeedController frontLeftSpeedMotor = RobotMap.driveTrainfrontLeftSpeedMotor;
    SpeedController frontRightDirMotor = RobotMap.driveTrainfrontRightDirMotor;
    SpeedController frontRigthSpeedMotor = RobotMap.driveTrainfrontRigthSpeedMotor;
    SpeedController rearLeftDirMotor = RobotMap.driveTrainrearLeftDirMotor;
    SpeedController rearLeftSpeedMotor = RobotMap.driveTrainrearLeftSpeedMotor;
    SpeedController rearRightDirMotor = RobotMap.driveTrainrearRightDirMotor;
    SpeedController rearRightSpeedMotor = RobotMap.driveTrainrearRightSpeedMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

	@Override
	public double getPIDSource(int marker) {
		return 0;
	}

	@Override
	public void setPIDOutput(double output, int marker) {
		
		
	}
}

